baseURL = "https://blog.oslab.top/"
languageCode = "en-us"
theme = 'hugo-bearblog'
title = "Hugo ʕ•ᴥ•ʔ Bear Blog"
author = "Jane Doe"
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]